### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by purrplingcat** [purrplingcat/PurrplingMod#7]
- [x] NPC can follow player
- [x] Save items to NPC's backpack
- [x] NPC "deliver" your saved items in their backpack to your home as package next morning
- [x] Fighting with enemies #6 
- [x] Variable dialogues support
- [x] Content support (json assets)
- [x] Content packs support #10 
- [x] Quests? #3 
- [x] Events? #3 
- [x] NPC proffesions/temperament #2 - DONE doctor, fighter and warrior
- [x] Allow asking NPCs in game progression (after companion introduction event)
- [x] More dialogues and content
- [x] Buffs and special effects for all NPCs

**This roadmap is outdated!**

Please see new roadmap: https://github.com/purrplingcat/PurrplingMod/projects/3
